spring.application.name=ToDoList

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update

# Swagger configuration
springdoc.swagger-ui.operations-sorter=alpha

# JWT configuration
jwt.secret=${JWT_KEY}
jwt.expiration=86400000